### ISSUE TITLE
关于新闻列表缩略图，可不可以设置成多张图片

### ISSUE THREAD

**Issue by ruiange** [zhuige-com/jiangqie_kafei#1]
您好，关于新闻列表接口，缩略图“thumbnail”，可不可以输出多张图片。
类似
![image](https://user-images.githubusercontent.com/21097765/78329111-68703000-75b3-11ea-80d0-b18bfbe7d2b8.png)
感觉全是一张图有点单调。

**Comment by longwenjunjie** [comment]
好的 这个后面会考虑

**Comment by jiangqie** [comment]
可以加微信：jianbing2011 加群交流，该功能新版本已列入计划中！
