### ISSUE TITLE
wordpress插接问题

### ISSUE THREAD

**Issue by Dean0731** [zhuige-com/jiangqie_kafei#2]
最近总是因为插件报错，wp站点出现错误，有的时候会自己好了，但出现的次数有点多。

**Comment by jiangqie** [comment]
> 最近总是因为插件报错，wp站点出现错误，有的时候会自己好了，但出现的次数有点多。

插件报错问题已修复。

**Comment by Dean0731** [comment]
我好像找到原因了，使用php7.4的时候就常出问题，换位php7.3就行了

**Comment by longwenjunjie** [comment]
多谢反馈
