### ISSUE TITLE
浏览量问题

### ISSUE THREAD

**Issue by anran-world** [zhuige-com/jiangqie_kafei#3]
你好 我想问一下，小程序的浏览量是存储在什么地方的，还是通过wp的某个函数获取的，我的今天浏览量突然归零了

**Comment by anran-world** [comment]
今天就下载了一个wp显示浏览量的插件，是不是与某些wp浏览量插件相关联啊

**Comment by longwenjunjie** [comment]
浏览量存储在wp_postmeta表中，meta_key 是 views，可能有其他插件或主题也用这个key。
