### ISSUE TITLE
wordpress开启多站点后子站点登陆无效

### ISSUE THREAD

**Issue by jacsice** [zhuige-com/jiangqie_kafei#5]
开启多站点后，只在主站点域名下登陆状态能保持，换成子站点域名，仍然走的主站点域名下的token校验，这个该怎么改呢？？

**Comment by jacsice** [comment]
已经解决了，因为开启子站点后，wordpress只复制了博客、评论相关的数据表，但是保存用户的wp_usermeta还是原来的，所以代码中的 $wpdb->prefix . 'usermeta'指向的是wp_2_usermeta，所以找不到用户。。
建议修改下check_login方法中的表名称

**Comment by longwenjunjie** [comment]
多谢反馈！🙏
