### ISSUE TITLE
首页上头条分类和菜单分类重复

### ISSUE THREAD

**Issue by wanghaisheng** [zhuige-com/jiangqie_kafei#8]
我跑起来了，但是发现首页头条那里其实就是文章分类，
然后又用了一个一级菜单分类是不是有些设计不合理
是否把一级菜单分类调整为标签 ，标签数量众多，这种展现的确能够帮助用户快速查找到对应的文章
我看了一下好像api目前并没有暴露标签的接口
@longwenjunjie

**Comment by longwenjunjie** [comment]
暂无此计划
如有需要，可参考 WordPress API，自行修改
